version: "3"

services:
  # Hosts the backend (API)
  backend:
    container_name: ljud-backend
    build:
      context: "./backend"
      dockerfile: "../docker/Dockerfile-backend"
    image: "ljud-backend"
    volumes:
      - ./backend/:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1 # don't wait for output to be flushed to stdout
    ports:
      - "8000:8000"

  # Hosts the soundfiles from upload folder in backend
  filehost:
    container_name: ljud-filehost
    build:
      context: "./docker"
      dockerfile: "Dockerfile-filehost"
    image: "ljud-filehost"
    volumes:
      - ./backend/uploads:/www/data
    ports:
      - "8080:80"

  # Hosts the frontend
  frontend:
    container_name: ljud-frontend
    build:
      context: "./frontend"
      dockerfile: "../docker/Dockerfile-frontend"
    image: "ljud-frontend"
    environment:
      - NODE_ENV=development # more debug info
      - "NEXT_WEBPACK_USEPOLLING=1"
    volumes:
      - ./frontend/:/modules/app
    ports:
     - "3000:3000"

