FROM python:3-alpine

WORKDIR /usr/src/app

RUN apk update
RUN apk add make automake gcc g++ subversion python3-dev ffmpeg


COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
CMD [ "uvicorn", "main:app", "--reload", "--host", "0.0.0.0" ]
